version: '3.9'
services:
  database:
    image: mysql:latest
    restart: on-failure
    environment:
      MYSQL_DATABASE: employee_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_ROOT_PASSWORD: abc123.

    ports:
      - "8092:3306"
    volumes:
      - db_data:/var/lib/mysql
    container_name: mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: abc123.
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - "8090:80"
    depends_on:
      - database
    container_name: pma
  
volumes:
  db_data: